apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  OPENAI_API_KEY: "<REPLACE>"
  DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/email_analyzer
