apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-analyzer
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: email-analyzer.freelancers-team.com
    http:
      paths:
      - path: /email-analyzer/api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: email-analyzer-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api-email-analyzer.freelancers-team.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
